export const siteConfig = {
  previewMode: true,
  businessName: "Everything Clean Cleaning Service",
  shortName: "Everything Clean",
  ownerName: "Michael Gonzalez",
  city: "Webster",
  state: "TX",
  phoneDisplay: "(832) 523-3941",
  phoneHref: "tel:+18325233941",
  smsHref: "sms:+18325233941",
  email: "michael@everythingcleantx.com",
  rating: "4.9",
  reviewCount: 100,
  hours: "7AM–7PM daily",
  services: [
    { title: "Home Cleaning", copy: "Detailed cleaning for homes and apartments, built around the spaces you actually live in." },
    { title: "Deep Cleaning", copy: "A more intensive reset for spaces that need extra attention from top to bottom." },
    { title: "Move-In / Move-Out", copy: "Cleaning for transitions, whether you're arriving, leaving, or preparing a property for what comes next." },
    { title: "Airbnb / Short-Term Rental", copy: "Turnover-focused cleaning for guest spaces and rental properties." },
    { title: "Office Cleaning", copy: "Professional cleaning for offices and workspaces." },
    { title: "Specialty Spaces", copy: "Public listings also reference patios, garages, and backyard cleanup work." },
  ],
  reviewThemes: [
    "Thorough attention to detail",
    "Fast, efficient work",
    "Professional and personable team",
    "Homes left spotless and fresh",
    "Strong deep-cleaning results",
  ],
  unknowns: [
    "Exact service-area cities",
    "Current pricing and package structure",
    "Recurring-cleaning cadence options",
    "Supplies / product policy",
    "Insurance or bonding status",
    "Cancellation and deposit policies",
    "Whether the Webster address is customer-facing",
  ],
} as const;
